---
deployment:
  tasks:
    - /bin/mkdir -p /home/mxafnahk/sazee.biz.id
    - /bin/cp -rf /home/mxafnahk/repositories/sazeeai/app/ /home/mxafnahk/sazee.biz.id/app/
    - /bin/cp -rf /home/mxafnahk/repositories/sazeeai/public/ /home/mxafnahk/sazee.biz.id/public/
    - /bin/cp -f /home/mxafnahk/repositories/sazeeai/composer.json /home/mxafnahk/sazee.biz.id/composer.json
    - /bin/cp -f /home/mxafnahk/repositories/sazeeai/spark /home/mxafnahk/sazee.biz.id/spark
    - /bin/cp -f /home/mxafnahk/repositories/sazeeai/preload.php /home/mxafnahk/sazee.biz.id/preload.php
    - /bin/cp -f /home/mxafnahk/repositories/sazeeai/index.php /home/mxafnahk/sazee.biz.id/index.php
    - /bin/cp -f /home/mxafnahk/repositories/sazeeai/.cpanel.yml /home/mxafnahk/sazee.biz.id/.cpanel.yml
