---
deployment:
  tasks:
    - /bin/mkdir -p /home/mxafnahk/sazee.biz.id
    - /bin/cp -ru /home/mxafnahk/repositories/sazeeai/app/ /home/mxafnahk/sazee.biz.id/app/
    - /bin/cp -ru /home/mxafnahk/repositories/sazeeai/public/ /home/mxafnahk/sazee.biz.id/public/
    - /bin/cp -ru /home/mxafnahk/repositories/sazeeai/writable/ /home/mxafnahk/sazee.biz.id/writable/
    - /bin/cp -f /home/mxafnahk/repositories/sazeeai/composer.json /home/mxafnahk/sazee.biz.id/composer.json
    - /bin/cp -f /home/mxafnahk/repositories/sazeeai/spark /home/mxafnahk/sazee.biz.id/spark
    - /usr/local/bin/php /home/mxafnahk/sazee.biz.id/spark migrate --no-interaction
